services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: precept
      POSTGRES_PASSWORD: precept
      POSTGRES_DB: precept
    volumes:
      - precept_pg:/var/lib/postgresql/data

volumes:
  precept_pg:
