import { z } from "zod";
import {
  AudioVisualRelationship,
  CameraAngle,
  CameraMovement,
  ColorPalette,
  Composition,
  ConnectionConfidence,
  ConnectionType,
  EmotionalRegister,
  LightingStyle,
  LocationType,
  MusicMood,
  MusicType,
  NarrativeFunction,
  SettingCategory,
  ShotScale,
  SoundDesignEmphasis,
  SubjectAction,
  TimeOfDay,
} from "./taxonomy.js";

export const filmSchema = z.object({
  title: z.string().min(1),
  year: z.number().int().min(1888),
  director: z.string().min(1),
  cinematographer: z.string().optional(),
  genre: z.array(z.string()).default([]),
  runtime_minutes: z.number().int().positive(),
  aspect_ratio: z.string().optional(),
  film_stock_or_camera: z.string().optional(),
  imdb_id: z.string().optional(),
  tmdb_id: z.number().int().optional(),
});

export const shotSchema = z.object({
  shot_index: z.number().int().nonnegative(),
  timecode_start: z.number().nonnegative(),
  timecode_end: z.number().nonnegative(),
  duration_seconds: z.number().nonnegative(),
  frames: z.array(z.string()).min(1),
  thumbnail: z.string(),
  audio_clip: z.string().optional(),
  shot_scale: z.nativeEnum(ShotScale),
  camera_angle: z.nativeEnum(CameraAngle),
  camera_movement: z.array(z.nativeEnum(CameraMovement)),
  composition: z.array(z.nativeEnum(Composition)),
  lighting: z.nativeEnum(LightingStyle),
  color_palette: z.array(z.nativeEnum(ColorPalette)),
  dominant_colors: z.array(z.string().regex(/^#[0-9A-Fa-f]{6}$/)).min(1),
  location_type: z.nativeEnum(LocationType),
  setting: z.nativeEnum(SettingCategory),
  time_of_day: z.nativeEnum(TimeOfDay),
  subject_count: z.number().int().nonnegative(),
  subject_actions: z.array(z.nativeEnum(SubjectAction)),
  emotional_register: z.array(z.nativeEnum(EmotionalRegister)),
  narrative_function: z.nativeEnum(NarrativeFunction),
  props_or_motifs: z.array(z.string()).optional(),
  music_present: z.boolean(),
  music_type: z.nativeEnum(MusicType).optional(),
  music_mood: z.nativeEnum(MusicMood).optional(),
  music_diegetic: z.boolean().optional(),
  audio_visual_relationship: z.nativeEnum(AudioVisualRelationship),
  sound_design: z.nativeEnum(SoundDesignEmphasis),
  dialogue_present: z.boolean(),
  specific_song: z.string().optional(),
  llm_description: z.string().min(1),
});

export const connectionSchema = z.object({
  source_shot_id: z.string().min(1),
  target_shot_id: z.string().min(1),
  connection_type: z.nativeEnum(ConnectionType),
  confidence: z.nativeEnum(ConnectionConfidence),
  description: z.string().optional(),
  evidence: z.string().optional(),
  similarity_score: z.number().min(0).max(1).optional(),
  created_by: z.enum(["system", "user", "ai"]),
});
